---

- name: create logrotate entry for ansible-pull.log
  ansible.builtin.template:
    src: 'etc/logrotate.d/potos-ansible-pull.j2'
    dest: '/etc/logrotate.d/{{ potos_basics_client_name | lower }}-ansible-pull'
    owner: root
    group: root
    mode: 0644

- name: install execution script
  ansible.builtin.template:
    src: 'usr/local/bin/potos-ansible-pull.j2'
    dest: "/usr/local/bin/{{ potos_basics_client_name | lower }}-ansible-pull"
    owner: root
    group: root
    mode: 0750

- name: install systemd service files
  ansible.builtin.template:
    src: "etc/systemd/system/potos-ansible-pull@.service.j2"
    dest: "/etc/systemd/system/{{ potos_basics_client_name | lower }}-ansible-pull@.service"
    owner: root
    group: root
    mode: 0644

- name: install systemd timer files
  ansible.builtin.template:
    src: "etc/systemd/system/potos-ansible-pull.timer.j2"
    dest: "/etc/systemd/system/{{ potos_basics_client_name | lower }}-ansible-pull-{{ item.runtype }}.timer"
    owner: root
    group: root
    mode: 0644
  vars:
    runtype: "{{ item.runtype }}"
    on_calendar: "{{ item.on_calendar | default(omit) }}"
  loop: "{{ potos_basics_runtypes | selectattr('runtype', 'defined') | selectattr('on_calendar', 'defined') }}"

- name: enable systemd timer/service
  ansible.builtin.systemd:
    name: "{{ potos_basics_client_name | lower }}-ansible-pull-{{ item }}.timer"
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
  loop: "{{ potos_basics_runtypes | selectattr('runtype', 'defined') | selectattr('on_calendar', 'defined') | map(attribute='runtype') }}"
  changed_when: false
