---
- name: Install python and pip
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - "python3"
    - "python3-pip"

- name: Install virtualenv
  ansible.builtin.pip:
    name: "virtualenv"

- name: Install Python env
  ansible.builtin.pip:
    name: "{{ item }}"
    virtualenv: "{{ potos_basics_ansible_workdir }}"
  loop:
    - "ansible-core=={{ potos_basics_ansible_version }}"
