---

- name: install generally required packages
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  loop: '{{ potos_basics_packages }}'

- name: create local work dir
  ansible.builtin.file:
    path: '{{ potos_basics_ansible_workdir }}'
    owner: root
    group: root
    mode: 0750
    state: directory

- name: create ansible inventory
  ansible.builtin.file:
    dest: "{{ potos_basics_ansible_inventory | dirname }}"
    owner: root
    group: root
    mode: 0750
    state: directory

- name: create ansible inventory
  ansible.builtin.copy:
    dest: "{{ potos_basics_ansible_inventory }}"
    content: "localhost ansible_connection=local"
    force: false

- name: create local log dir
  ansible.builtin.file:
    path: '{{ potos_basics_ansible_logdir }}'
    owner: root
    group: root
    mode: 0750
    state: directory

- name: ansible ansible-env
  ansible.builtin.include_tasks: ansible-env.yml

- name: ansible ansible-pull
  ansible.builtin.include_tasks: ansible-pull.yml
