---

- name: check if ansible-vault-key is installed
  ansible.builtin.stat:
    path: '/etc/potos/etc/potos/ansible_vault_key'
  register: potos_basics_ansible_vault_key_check

- name: install generally required packages
  ansible.builtin.package:
    name: "{{ potos_basics_packages }}"
    state: "{{ potos_basics_packages_enforce_latest | ternary('latest', 'present') }}"

- name: create local work dir
  ansible.builtin.file:
    path: '{{ potos_basics_ansible_workdir }}'
    owner: root
    group: root
    mode: 0750
    state: directory

- name: check playbook out
  ansible.builtin.git:
    repo: "https://github.com/projectpotos/ansible-plays-potos.git"
    dest: "{{ potos_basics_ansible_workdir }}"
    version: "{{ potos_basics_playbook_version }}"

- name: create ansible inventory
  ansible.builtin.file:
    dest: "{{ potos_basics_ansible_inventory | dirname }}"
    owner: root
    group: root
    mode: 0750
    state: directory

- name: get hostname
  shell: hostname -f
  register: potos_basics_hostname

- name: create ansible inventory
  ansible.builtin.copy:
    dest: "{{ potos_basics_ansible_inventory }}"
    content: "{{ potos_basics_hostname }} ansible_connection=local"
    force: false
    owner: root
    group: root
    mode: 0640

- name: create local log dir
  ansible.builtin.file:
    path: '{{ potos_basics_ansible_logdir }}'
    owner: root
    group: root
    mode: 0750
    state: directory

- name: ansible ansible-env
  ansible.builtin.include_tasks: ansible-env.yml

- name: ansible ansible-pull
  ansible.builtin.include_tasks: ansible-pull.yml

- name: legacy cleanup
  ansible.builtin.include_tasks: legacy-cleanup.yml
